# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

aws: &aws
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

activecampaign: &activecampaign
  ac_key: <%= ENV["AC_KEY"] %>
  ac_endpoint: <%= ENV["AC_ENDPOINT"] %>

development:
  secret_key_base: 6d9c355abbb0ea250502386c5f987030ca5e4ed2f6040ed644043ac72154ebf637779b6d601cdcf22d92cbb931043090163f3052b365f3582c8644075858e14f
  <<: *activecampaign

test:
  secret_key_base: e357b019579e32e1e2e355778675b60c1858f2f43dfe4b12cde39715c8e25341c5cc043b11101d55b12892c6f482a52d98308f85a651a4afa9bc918a8510a755
  <<: *activecampaign

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *aws
  <<: *activecampaign

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *aws
  <<: *activecampaign
